version=0.1
[default.global.parameters]
stack_name = "skp-app"

[default.deploy.parameters]
stack_name = "skp-app"
capabilities = "CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND"
confirm_changeset = true
region = "us-east-1"
s3_bucket = "bs-skp-workspace"
s3_prefix = "sam/repo/skp-app"
parameter_overrides=[
    "sourceBucket=skp-app",
    "destinationBucket=skp-app",
    "sourcePrefix=misc/",
    "destinationPrefix=misc/",
    "env=dev",
    "retailerDomain=www.esshopzilla.com",
    "checkoutPageName=https://www.esshopzilla.com/checkout/?a=complete",
    "inputFileName=data.tsv"
    ]

[dev.deploy.parameters]
stack_name = "skp-app"
capabilities = "CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND"
confirm_changeset = true
region = "us-east-1"
s3_bucket = "bs-skp-workspace"
s3_prefix = "sam/repo/skp-app"
parameter_overrides=[
    "sourceBucket=skp-app",
    "destinationBucket=skp-app",
    "sourcePrefix=misc/",
    "destinationPrefix=misc/",
    "env=dev",
    "retailerDomain=www.esshopzilla.com",
    "checkoutPageName=https://www.esshopzilla.com/checkout/?a=complete",
    "inputFileName=data.tsv"
    ]

[qa.deploy.parameters]
stack_name = "skp-app"
capabilities = "CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND"
confirm_changeset = true
region = "us-east-1"
s3_bucket = "bs-skp-workspace-qa"
s3_prefix = "sam/repo/skp-app"
parameter_overrides=[
    "sourceBucket=skp-app",
    "destinationBucket=skp-app",
    "sourcePrefix=misc/",
    "destinationPrefix=misc/",
    "env=qa",
    "retailerDomain=www.esshopzilla.com",
    "checkoutPageName=https://www.esshopzilla.com/checkout/?a=complete",
    "inputFileName=data.tsv"
    ]

[prod.deploy.parameters]
stack_name = "skp-app"
capabilities = "CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND"
confirm_changeset = true
region = "us-east-1"
s3_bucket = "bs-skp-workspace-prod"
s3_prefix = "sam/repo/skp-app"
parameter_overrides=[
    "sourceBucket=skp-app",
    "destinationBucket=skp-app",
    "sourcePrefix=misc/",
    "destinationPrefix=misc/",
    "env=prod",
    "retailerDomain=www.esshopzilla.com",
    "checkoutPageName=https://www.esshopzilla.com/checkout/?a=complete",
    "inputFileName=data.tsv"
    ]

